@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Component(cli, "CLI", "", $techn="CLI - Command Line Interface")
Component(api, "API", "", $techn="API - Application Programing Interface")
ContainerDb(db, "Database")

Container_Boundary(application, "Application") {
 Component(createAccount, "CreateAccount", "execute")
 Component(query, "Query DAO", "getAccount")

 Rel(createAccount, query, "Uses")
}

Rel(query, db, "Uses")
Rel(cli, createAccount, "Uses")
Rel(api, createAccount, "Uses")
@enduml