@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Component(cli, "CLI", "", $techn="CLI - Command Line Interface")
Component(api, "API", "", $techn="API - Application Programing Interface")
Component(test, "Test", "", $techn="")
ContainerDb(db, "Database")

Container_Boundary(application, "Application") {
 Component(transactionDeposit, "TransactionDeposit", "execute")
 Component(transaction, "Transaction", "create")
 Component(account, "AccountDomain", "create")
 Component(accountRepository, "AccountRepository", "save")
 Component(transactionRepository, "TransactionRepository", "save")

 Rel(transactionDeposit, account, "Uses")
 Rel(transactionDeposit, transaction, "Uses")
 Rel(transactionDeposit, accountRepository, "Uses")
 Rel(transactionDeposit, transactionRepository, "Uses")
}

Rel(accountRepository, db, "Uses")
Rel(transactionRepository, db, "Uses")
Rel(cli, transactionDeposit, "Uses")
Rel(api, transactionDeposit, "Uses")
Rel(test, transactionDeposit, "Uses")
@enduml