@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Component(cli, "CLI", "", $techn="CLI - Command Line Interface")
Component(api, "API", "", $techn="API - Application Programing Interface")
Component(test, "Test", "", $techn="")
ContainerDb(db, "Database")

Container_Boundary(application, "Application") {
 Component(transactionWithdraw, "TransactionWithdraw", "execute")
 Component(transaction, "Transaction", "create")
 Component(account, "AccountDomain", "create")
 Component(accountRepository, "AccountRepository", "save")
 Component(transactionRepository, "TransactionRepository", "save")

 Rel(transactionWithdraw, account, "Uses")
 Rel(transactionWithdraw, transaction, "Uses")
 Rel(transactionWithdraw, accountRepository, "Uses")
 Rel(transactionWithdraw, transactionRepository, "Uses")
}

Rel(accountRepository, db, "Uses")
Rel(transactionRepository, db, "Uses")
Rel(cli, transactionWithdraw, "Uses")
Rel(api, transactionWithdraw, "Uses")
Rel(test, transactionWithdraw, "Uses")
@enduml