@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Component(cli, "CLI", "", $techn="CLI - Command Line Interface")
Component(api, "API", "", $techn="API - Application Programing Interface")
ContainerDb(db, "Database")

Container_Boundary(application, "Application") {
 Component(query, "Query DAO", "listTransaction")
}

Rel(query, db, "Uses")
Rel(cli, query, "Uses")
Rel(api, query, "Uses")
@enduml