@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Component(cli, "CLI", "", $techn="CLI - Command Line Interface")
Component(api, "API", "", $techn="API - Application Programing Interface")
Component(test, "Test", "", $techn="")
ContainerDb(db, "Database")

Container_Boundary(application, "Application") {
 Component(updateAccountLimit, "UpdateAccountLimit", "execute")
 Component(account, "AccountDomain", "create")
 Component(accountRepository, "AccountRepository", "update")

 Rel(updateAccountLimit, account, "Uses")
 Rel(updateAccountLimit, accountRepository, "Uses")
}

Rel(accountRepository, db, "Uses")
Rel(cli, updateAccountLimit, "Uses")
Rel(api, updateAccountLimit, "Uses")
Rel(test, updateAccountLimit, "Uses")
@enduml